/* NLIBRand.c
 * Marco Morais												6/6/00
 * Includes random number functions for different distributions.
 */
 
#include "NLIBRand.h"

 /*****************************/
 /*   RANDOM NUMBER FUNCTIONS */
 /*****************************/

/*---------------------------------------------------------------------*/
void randinit (long s) 
/*---------------------------------------------------------------------*/
{
/* Description: Seed the random number generator with the seed s.  Each
                seed produces a different random sequence.
                
   On entry:    s = long integer specifying the seed.  If s < 0,
                then a random seed based on the time of the day is
                generated.

   Notes:       If a random seed (s <= 0) is selected, then a
                different random sequence will be generated by
                functions randu and randg each time a program
                that uses them is executed. The default seed is
                s = 1 */
                
   if (s > 0)
      randi (s);
   else
      randi (-1);
}
      
/*---------------------------------------------------------------------*/
long randi (long u) 
/*---------------------------------------------------------------------*/
{
/* Description: Generate the next random integer in the sequence.

   On entry:    u = opteating mode:

                    u > 0  =>  initialize random sequence with seed q
                    u = 0  =>  return next random number in sequence
                    u < 0  =>  initialize random sequence base on
                               time of day. */

   static long
                LSEED = 1;                 /* current random integer */
   long
                q = 127773L,
                r = 2836L,
                alpha = 16807L;

   if      (u > 0)
      LSEED = u; 
   else if (u < 0)
      LSEED = time (NULL);
   else
   {             
      LSEED = alpha*(LSEED % q) - r*(LSEED/q);
      if (LSEED < 0)
         LSEED += LRAND_MAX;
   }      
   return LSEED;
}

/*---------------------------------------------------------------------*/
float randu (float a,float b) {
/*---------------------------------------------------------------------*/

/* Description: Generate the next random real number uniformly
                distributed over the interval [a,b].

   On entry:    a = lower limit on value of random number
                b = upper limit on value of random number

   Notes:       The random number generator is seeded with the
                function randinit. */

   float	x,y;
   double   d; 
   static long	t[64];
   static int	rand_init = 0;
   int		i,n=64;
   
/* Initialize */

   y = (float) n;
   if (!rand_init) {
      for (i = 0; i < n; i++)
         t[i] = randi(0);    
      rand_init = 1; }

/*  Generate a random index i and output t[i], then update */

   d = y*randi(0)/(LRAND_MAX + 1.0);
   i = (int) d;
   x = (float) t[i];
   t[i] = randi(0);
   return (a + (b-a)*x/LRAND_MAX); }                

/*---------------------------------------------------------------------*/
float randg (float m,float s) {
/*---------------------------------------------------------------------*/

/* Description: Generate the next random real number with a
                Gaussian distribution with mean m and standard
                deviation s > 0.

   On entry:    m = desired mean value
                s = desired standard deviation (s > 0)

   Notes:       The random number generator is seeded with the
                function randinit. */

   float x1,x2;
   double y;
   x1 = randu (0,1);
   x2 = randu (0,1);
   y = sqrt(-2*log(x1))*cos(2*PI*x2);
   return (float) (m + s*y); 
   }
   
/* end of NLIBRand.c */
