/*! 
 * \file FireProp.c
 *  
 * \author Marco Morais
 * \date 2000-2001 
 *
 *	HFire (Highly Optmized Tolerance Fire Spread Model) Library
 *	Copyright (C) 2001 Marco Morais
 *
 *	This library is free software; you can redistribute it and/or
 *	modify it under the terms of the GNU Lesser General Public
 *	License as published by the Free Software Foundation; either
 *	version 2.1 of the License, or (at your option) any later version.
 *
 *	This library is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *	Lesser General Public License for more details.
 *
 *	You should have received a copy of the GNU Lesser General Public
 *	License along with this library; if not, write to the Free Software
 *	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
 
#include "FireProp.h"

static const char * propstr [] = {
	"SIMULATION_START_YEAR",
	"SIMULATION_START_MONTH",
	"SIMULATION_START_DAY",
	"SIMULATION_START_HOUR",
	"SIMULATION_END_YEAR",	
	"SIMULATION_END_MONTH",	
	"SIMULATION_END_DAY",		
	"SIMULATION_END_HOUR",
	"SIMULATION_TIMESTEP_SECS",	
	"SIMULATION_RAND_NUM_SEED",
	"FUELS_PROPS_TYPE",	
	"FUELS_PROPS_FMD_FILE",
	"FUELS_PROPS_FM_NUMS_IMPORT",
	"FUELS_PROPS_FM_NUMS_UNBURNABLE",
	"ELEV_RASTER_FORMAT",	
	"ELEV_RASTER_MAIN_FILE",		
	"ELEV_RASTER_HEADER_FILE",	
	"ELEV_RASTER_TYPE",		
	"SLOPE_RASTER_FORMAT",
	"SLOPE_RASTER_MAIN_FILE",	
	"SLOPE_RASTER_HEADER_FILE",	
	"SLOPE_RASTER_TYPE",			
	"ASPECT_RASTER_FORMAT",
	"ASPECT_RASTER_MAIN_FILE",	
	"ASPECT_RASTER_HEADER_FILE",
	"ASPECT_RASTER_TYPE",
	"EXPORT_FREQUENCY",
	"EXPORT_FIRE_ID_RASTER_DIR",
	"EXPORT_FUELS_RASTER_DIR",
	"EXPORT_STAND_AGE_RASTER_DIR",
	"EXPORT_FIRE_AREA_FILE",
	"EXPORT_FIRE_PERIMTER_FILE",
	"EXPORT_IGNITION_LOCS_FILE",
	"EXPORT_SANTA_ANA_EVT_FILE",	
	"EXPORT_FIRE_ID_PNG_DIRECTORY",
	"EXPORT_FIRE_ID_PNG_ICM_FILE",
	"EXPORT_FIRE_ID_PNG_IMG_WIDTH",
	"EXPORT_FIRE_ID_PNG_IMG_HGT",
	"EXPORT_FIRE_ID_PNG_TITLE_TXT",
	"EXPORT_FIRE_ID_PNG_TITLE_FNT",
	"EXPORT_FIRE_ID_PNG_TITLE_POS",	
	"FIRE_EXTINCTION_TYPE",
	"FIRE_EXTINCTION_HOURS",
	"FIRE_EXTINCTION_ROS_MPS",
	"FUELS_REGROWTH_TYPE",
	"FUELS_FIXED_MODEL_NUM",
	"FUELS_PNV_RGR_FILE",
	"FUELS_PNV_RASTER_FORMAT",
	"FUELS_PNV_RASTER_MAIN_FILE",
	"FUELS_PNV_RASTER_HEADER_FILE",
	"FUELS_PNV_RASTER_TYPE",
	"FUELS_STATIC_RASTER_FORMAT",
	"FUELS_STATIC_RASTER_MAIN_FILE",
	"FUELS_STATIC_RASTER_HEADER_FILE",
	"FUELS_STATIC_RASTER_TYPE",
	"STAND_AGE_TYPE",
	"STAND_AGE_FIXED_AGE",	
	"STAND_AGE_RASTER_FORMAT",
	"STAND_AGE_RASTER_MAIN_FILE",
	"STAND_AGE_RASTER_HEADER_FILE",
	"STAND_AGE_RASTER_TYPE",	
	"IGNITION_TYPE",
	"IGNITION_FIXED_IGS_FILE",
	"IGNITION_FREQUENCY_PER_YEAR",
	"IGNITION_RSP_RASTER_FORMAT",
	"IGNITION_RSP_RASTER_MAIN_FILE",
	"IGNITION_RSP_RASTER_HEADER_FILE",
	"IGNITION_RSP_RASTER_TYPE",
	"WIND_AZIMUTH_TYPE",
	"WIND_AZIMUTH_HISTORICAL_FILE",
	"WIND_AZIMUTH_FIXED_FILE",
	"WIND_AZIMUTH_SPATIAL_FILE",	
	"WIND_SPEED_TYPE",
	"WIND_SPEED_HISTORICAL_FILE",
	"WIND_SPEED_FIXED_FILE",
	"WIND_SPEED_SPATIAL_FILE",
	"WIND_SPEED_UNIFORM_RANGE",
	"DEAD_FUEL_MOIST_TYPE",
	"DEAD_FUEL_MOIST_HISTORICAL_FILE",
	"DEAD_FUEL_MOIST_FIXED_FILE",
	"DEAD_FUEL_MOIST_SPATIAL_FILE",
	"LIVE_FUEL_MOIST_TYPE",
	"LIVE_FUEL_MOIST_HERB_FILE",
	"LIVE_FUEL_MOIST_WOOD_FILE",
	"LIVE_FUEL_MOIST_SPATIAL_FILE",
	"SANTA_ANA_FREQUENCY_PER_YEAR",
	"SANTA_ANA_NUM_DAYS_DURATION",
	"SANTA_ANA_WIND_AZIMUTH_FILE",
	"SANTA_ANA_WIND_SPEED_FILE",
	"SANTA_ANA_DEAD_FUEL_MOIST_FILE",
  "FIRE_ELLIPSE_ADJUSTMENT_FACTOR",
  "WIND_SPEED_WIND_ADJUSTMENT_FACTOR",
  "DEAD_FUEL_MOIST_D1H_INCREMENT",
  "DEAD_FUEL_MOIST_D100H_INCREMENT",
  "EXPORT_FIRE_INFO_FILE",
  "FIRE_FAILED_IGNITION_NUM_CELLS",
  "EXPORT_SANTA_ANA_RASTER_DIR",
  "EXPORT_AGE_AT_BURN_HIST_FILE"
};

static const char * valstr [] =	{
	"ASCII",
	"BINARY",
	"NULL",
	"DOUBLE",
	"FLOAT",
	"LONGINT",
	"INT",
	"BYTE",
	"FIXED",
	"PNV",
	"STATIC",
	"SPATIAL",
	"RANDOM_UNIFORM",
	"RANDOM_HISTORICAL",
	"RANDOM_SPATIAL",
	"TABLE",
	"TIMESTEP",
	"DAILY",	
	"ANNUAL",
	"TINY",
	"SMALL",
	"MEDBOLD",
	"LARGE",
	"GIANT",
	"UL",
	"LL",
	"LR",
	"UR",
	"CONSUME",
	"REIGNITE",
	"ROTH",
	"PHYS",
  "AB79",
  "BHP",
  "NOWAF"
};
	
const char * GetFireProp(EnumFireProp p)	{
	return propstr[p];
}

const char * GetFireVal(EnumFireVal v)	{
	return valstr[v];
}
	
/* end of FireProp.c */
